### ISSUE TITLE
how to visualize execution PLANS?

### ISSUE THREAD

**Issue by VladimirAlexiev** [sib-swiss/sparql-examples-utils#12]
Another excellent idea is to visualize execution PLANS. But there the order of execution (trying patterns) matters: how could this be shown?

PS: I like these diagrams a lot, so I posted an issue to integrate them in GraphDB Workbench: https://ontotext.atlassian.net/browse/GDB-10923

**Comment by JervenBolleman** [comment]
I won't be working in this utils project on visualizing query plans.

**Comment by VladimirAlexiev** [comment]
Sorry Jerven: https://github.com/w3c/sparql-dev/issues/203
